apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nzfkc3i5a-java-springboot
  janus-idp.io/tekton: nzfkc3i5a-java-springboot
  backstage.io/kubernetes-id: nzfkc3i5a-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nzfkc3i5a-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
